name: demo1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_auth: ^4.17.1
  firebase_core: ^2.30.1
  cloud_firestore: ^4.17.3
  scratcher: ^2.0.0
  flutter_fortune_wheel: ^1.2.0
  shared_preferences: ^2.2.2
  google_mobile_ads: ^5.0.0
  google_sign_in: ^6.1.5
  crypto: ^3.0.6
  url_launcher: ^6.2.6
  font_awesome_flutter: ^10.7.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.png